### ISSUE TITLE
demo jQuery missing

### ISSUE THREAD

**Issue by benfoxall** [thom4parisot/content-edit#8]
I have a feel that this is me not pulling down the project properly (I cloned the repo rather than getting set up with bower).

The demo linked to a jQuery file - '../src/vendor/jquery/jquery.min.js' - that doesn't exist.

I started making a PR linking to the google cdn version - though wasn't sure that's what you wanted

**Comment by thom4parisot** [comment]
Yep I should provide better instructions if pulling the content directly from git.

Just run `npm install` after the checkout, it will pull and build the dependencies for you.
